set -g history-limit 1000000
set -g allow-rename off

set-window-option -g mode-keys vi


# Git Clone Tmux Plugins Module
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Other plugins
# set -g @plugin 'github_username/plugin_name'

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'

# Logging plugin
set -g @plugin 'tmux-plugins/tmux-logging'